apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongouser: {{ .Values.mongo.secret.values.mongouser }}
  mongopassword: {{ .Values.mongo.secret.values.mongopassword }}
