apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  labels:
    app: task-io-mongo
spec:
  replicas: {{ .Values.mongo.statefulset.replicasCount }}
  selector:
    matchLabels:
      app: task-io-mongo
  template:
    metadata:
      labels:
        app: task-io-mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: {{ .Values.mongo.statefulset.ports.containerListenPort }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongopassword
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: task-io-mongo-service
spec:
  selector:
    app: task-io-mongo
  ports:
    - protocol: TCP
      port: {{ .Values.mongo.service.ports.listenPort }}
      targetPort: {{ .Values.mongo.service.ports.targetPort }}
