apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
  labels:
    app: task-io-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-io-rabbitmq
  template:
    metadata:
      labels:
        app: task-io-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.7-management
          imagePullPolicy: Never
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: task-io-rabbitmq-service
spec:
  type: NodePort
  selector:
    app: task-io-rabbitmq
  ports:
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: management
      port: 15672
      targetPort: 15672
      nodePort: 30100
