apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-io-projects-deployment
  labels:
    app: task-io-projects
spec:
  replicas: {{ .Values.projects.deployment.replicasCount }}
  selector:
    matchLabels:
      app: task-io-projects
  template:
    metadata:
      labels:
        app: task-io-projects
    spec:
      containers:
        - name: task-io-projects
          image: pyankovdaniil/task-io-projects:1.0.0
          imagePullPolicy: Never
          ports:
            - name: rest
              containerPort: {{ .Values.projects.deployment.ports.restContainerListenPort }}
          env:
            - name: PROJECTS_SERVER_PORT
              value: "{{ .Values.projects.serverPort | toString }}"
            - name: PROJECTS_APPLICATION_NAME
              value: {{ .Values.projects.applicationName }}
            - name: LOGGING_ROOT_LEVEL
              value: {{ .Values.projects.loggingLevels.root }}
            - name: LOGGING_API_LEVEL
              value: {{ .Values.projects.loggingLevels.api }}
            - name: MONGO_DATABASE
              value: {{ .Values.projects.mongo.database }}
            - name: AUTHENTICATION_HEADER_NAME
              value: {{ .Values.authentication.headers.authenticationHeaderName }}
            - name: MONGO_AUTHENTICATION_DATABASE
              value: {{ .Values.mongo.authenticationDatabase }}
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongouser
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongopassword
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: MONGO_PORT
              value: "{{ .Values.mongo.service.ports.listenPort | toString }}"
---
apiVersion: v1
kind: Service
metadata:
  name: task-io-projects-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: task-io-projects
  ports:
    - protocol: TCP
      name: rest
      port: {{ .Values.projects.service.ports.rest.listenPort }}
      targetPort: {{ .Values.projects.service.ports.rest.targetPort }}
