apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-io-notification-deployment
  labels:
    app: task-io-notification
spec:
  replicas: {{ .Values.notification.deployment.replicasCount }}
  selector:
    matchLabels:
      app: task-io-notification
  template:
    metadata:
      labels:
        app: task-io-notification
    spec:
      containers:
        - name: task-io-notification
          image: pyankovdaniil/task-io-notification:1.0.0
          imagePullPolicy: Never
          ports:
            - name: rest
              containerPort: {{ .Values.notification.deployment.ports.restContainerListenPort }}
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: rabbitmq-url
---
apiVersion: v1
kind: Service
metadata:
  name: task-io-notification-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: task-io-notification
  ports:
    - protocol: TCP
      name: rest
      port: {{ .Values.notification.service.ports.rest.listenPort }}
      targetPort: {{ .Values.notification.service.ports.rest.targetPort }}
