apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-io-projects-deployment
  labels:
    app: task-io-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-io-projects
  template:
    metadata:
      labels:
        app: task-io-projects
    spec:
      containers:
        - name: task-io-projects
          image: pyankovdaniil/task-io-projects
          ports:
            - name: rest
              containerPort: 8082
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: task-io-projects-service
spec:
  type: LoadBalancer
  selector:
    app: task-io-projects
  ports:
    - protocol: TCP
      name: rest
      port: 8082
      targetPort: 8082
