apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-io-authentication-deployment
  labels:
    app: task-io-authentication
spec:
  replicas: {{ .Values.authentication.deployment.replicasCount }}
  selector:
    matchLabels:
      app: task-io-authentication
  template:
    metadata:
      labels:
        app: task-io-authentication
    spec:
      containers:
        - name: task-io-authentication
          image: pyankovdaniil/task-io-authentication:1.0.0
          imagePullPolicy: Never
          ports:
            - name: rest
              containerPort: {{ .Values.authentication.deployment.ports.restContainerListenPort }}
          env:
            - name: AUTHENTICATION_SERVER_PORT
              value: "{{ .Values.authentication.serverPort | toString }}"
            - name: AUTHENTICATION_APPLICATION_NAME
              value: {{ .Values.authentication.applicationName }}
            - name: LOGGING_ROOT_LEVEL
              value: {{ .Values.authentication.loggingLevels.root }}
            - name: LOGGING_API_LEVEL
              value: {{ .Values.authentication.loggingLevels.api }}
            - name: AUTHENTICATION_HEADER_NAME
              value: {{ .Values.authentication.headers.authenticationHeaderName }}
            - name: AUTHENTICATION_HEADER_PREFIX
              value: {{ .Values.authentication.headers.authenticationHeaderPrefix }}
            - name: EMAIL_VERIFICATION_CODE_LENGTH
              value: "{{ .Values.authentication.emailVerificationCodeLength | toString }}"
            - name: MONGO_AUTHENTICATION_DATABASE
              value: {{ .Values.mongo.authenticationDatabase }}
            - name: MONGO_DATABASE
              value: {{ .Values.authentication.mongo.database }}
            - name: JWT_SECRET_KEY
              value: {{ .Values.authentication.jwt.secretKey }}
            - name: JWT_ACCESS_TOKEN_EXPIRE_TIME_MS
              value: "{{ .Values.authentication.jwt.accessTokenExpireTimeMs | toString }}"
            - name: JWT_REFRESH_TOKEN_EXPIRE_TIME_MS
              value: "{{ .Values.authentication.jwt.refreshTokenExpireTimeMs | toString }}"
            - name: RABBITMQ_INTERNAL_EXCHANGE
              value: {{ .Values.rabbitmq.exchanges.internal }}
            - name: RABBITMQ_INTERNAL_NOTIFICATION_ROUTING_KEY
              value: {{ .Values.rabbitmq.routingKeys.internalNotification }}
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongouser
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongopassword
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: MONGO_PORT
              value: "{{ .Values.mongo.service.ports.listenPort | toString }}"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-url
            - name: REDIS_PORT
              value: "{{ .Values.redis.service.ports.listenPort | toString }}"
---
apiVersion: v1
kind: Service
metadata:
  name: task-io-authentication-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: task-io-authentication
  ports:
    - protocol: TCP
      name: rest
      port: {{ .Values.authentication.service.ports.rest.listenPort }}
      targetPort: {{ .Values.authentication.service.ports.rest.targetPort }}
