apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-io-authentication-deployment
  labels:
    app: task-io-authentication
spec:
  replicas: {{ .Values.authentication.deployment.replicasCount }}
  selector:
    matchLabels:
      app: task-io-authentication
  template:
    metadata:
      labels:
        app: task-io-authentication
    spec:
      containers:
        - name: task-io-authentication
          image: pyankovdaniil/task-io-authentication:1.0.0
          imagePullPolicy: Never
          ports:
            - name: rest
              containerPort: {{ .Values.authentication.deployment.ports.restContainerListenPort }}
            - name: grpc
              containerPort: {{ .Values.authentication.deployment.ports.grpcContainerListenPort }}
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongouser
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongopassword
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-url
---
apiVersion: v1
kind: Service
metadata:
  name: task-io-authentication-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: task-io-authentication
  ports:
    - protocol: TCP
      name: rest
      port: {{ .Values.authentication.service.ports.rest.listenPort }}
      targetPort: {{ .Values.authentication.service.ports.rest.targetPort }}
    - protocol: TCP
      name: grpc
      port: {{ .Values.authentication.service.ports.grpc.listenPort }}
      targetPort: {{ .Values.authentication.service.ports.grpc.targetPort }}
