apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  rabbitmquser: {{ .Values.rabbitmq.secret.values.rabbitmquser }}
  rabbitmqpassword: {{ .Values.mongo.secret.values.rabbitmqpassword }}
