package taskio.common.dto.errors;

public enum ErrorCode {
    USER_ALREADY_EXIST_IN_DATABASE,
    USER_NOT_FOUND_BY_EMAIL_IN_DATABASE,
    INVALID_TOKEN,
    INVITER_IS_NOT_A_MEMBER,
    PASSWORD_NOT_MATCH,
    USER_ALREADY_CREATED_THIS_PROJECT,
    USER_ALREADY_IS_IN_PROJECT,
    USER_WAS_NOT_INVITED_TO_A_PROJECT,
}
