authentication:
  deployment:
    replicasCount: 1
    ports:
      restContainerListenPort: 8080
      grpcContainerListenPort: 8081
  service:
    ports:
      rest:
        listenPort: 8080
        targetPort: 8080
      grpc:
        listenPort: 8081
        targetPort: 8081
projects:
  deployment:
    replicasCount: 1
    ports:
      restContainerListenPort: 8082
  service:
    ports:
      rest:
        listenPort: 8082
        targetPort: 8082
notification:
  deployment:
    replicasCount: 1
    ports:
      restContainerListenPort: 8083
  service:
    ports:
      rest:
        listenPort: 8083
        targetPort: 8083
mongo:
  secret:
    values:
      mongouser: dXNlcg==
      mongopassword: cGFzc3dvcmQ=
  statefulset:
    replicasCount: 1
    ports:
      containerListenPort: 27017
  service:
    ports:
      listenPort: 27017
      targetPort: 27017
redis:
  statefulset:
    replicasCount: 1
    ports:
      containerListenPort: 6379
  service:
    ports:
      listenPort: 6379
      targetPort: 6379
rabbitmq:
  statefulset:
    replicasCount: 1
    ports:
      amqpContainerListenPort: 5672
      managementContainerListenPort: 15672
  service:
    ports:
      amqpContainerListenPort: 5672
      managementContainerListenPort: 15672
      managementContainerNodePort: 30100